import {
  Package,
  CupSoda,
  PawPrint,
  Shirt,
  ShoppingBag,
  Gift,
  Tags,
  Sparkles,
  Watch,
  Footprints,
  Heart,
  Baby,
  Home,
  Star,
  Smartphone,
  Tablet,
  Laptop,
  Headphones,
  Camera,
  Glasses,
  Gem,
  Wallet,
  Backpack,
  Lamp,
  BookOpen,
  Utensils,
  Car,
  Bike,
  Tv,
  Speaker,
  SprayCan,
  Flower2,
  Dumbbell,
  Guitar,
  Umbrella,
  Sofa,
  LucideIcon,
} from "lucide-react";

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  package: Package,
  cup: CupSoda,
  toys: PawPrint,
  shirt: Shirt,
  bag: ShoppingBag,
  gift: Gift,
  tags: Tags,
  sparkles: Sparkles,
  watch: Watch,
  shoe: Footprints,
  heart: Heart,
  baby: Baby,
  home: Home,
  star: Star,
  smartphone: Smartphone,
  tablet: Tablet,
  laptop: Laptop,
  headphones: Headphones,
  camera: Camera,
  glasses: Glasses,
  gem: Gem,
  wallet: Wallet,
  backpack: Backpack,
  lamp: Lamp,
  book: BookOpen,
  utensils: Utensils,
  car: Car,
  bike: Bike,
  tv: Tv,
  speaker: Speaker,
  spray: SprayCan,
  flower: Flower2,
  dumbbell: Dumbbell,
  guitar: Guitar,
  umbrella: Umbrella,
  sofa: Sofa,
};

export const CATEGORY_ICON_KEYS = Object.keys(CATEGORY_ICONS);

export function CategoryIcon({ icon, className }: { icon?: string | null; className?: string }) {
  const Icon = CATEGORY_ICONS[icon ?? ""] ?? Package;
  return <Icon className={className ?? "w-4 h-4"} />;
}